#! /bin/sh
### BEGIN INIT INFO
# Provides:          kaeng
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

# Do NOT "set -e"

# Node Path is where you installed node
NODEPATH=/opt/node/bin
# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=$NODEPATH:/sbin:/usr/sbin:/bin:/usr/bin

case "$1" in
  start)
	(cd /opt/kaeng; /usr/bin/nohup /usr/local/bin/node kaeng.js --config file://proxyroutes.json&)
	;;
  stop)
	;;
  reload|restart)
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
	exit 3
	;;
esac

